let _uid = 1;
export const uid = () => String(++_uid);

export const mkTask = (o = {}) => ({
  id: uid(), action: '', person: 'SS', due: '', priority: 'Medium',
  status: 'Not Started', thisWeek: false, manualFlag: false, ...o,
});

export const mkRow = (label, name, comments, tasks) => ({
  id: uid(), label, name: name || '', comments: comments || '',
  tasks: (tasks || [{}]).map(t => mkTask(t)),
});

export const PERSON_LIST = [
  { id: 'CS',    label: 'Carson Bolt' },
  { id: 'SS',    label: 'Shannon Sharp' },
  { id: 'AL',    label: 'Assem Labib' },
  { id: 'ALL',   label: 'Everyone' },
  { id: 'CB/SS', label: 'Carson & Shannon' },
  { id: 'SS/AL', label: 'Shannon & Assem' },
  { id: 'CS/AL', label: 'Carson & Assem' },
  { id: 'Ext',   label: 'External' },
];

export const PRIORITIES = ['High', 'Medium', 'Low'];
export const STATUSES   = ['Not Started', 'In Progress', 'Awaiting Response', 'Completed', 'On Hold'];
export const STAGES     = ['Land Acquisition', 'Planning & Approvals', 'Construction', 'Sales & Settlements', 'Finance & Budget'];

export const SECTION_META = [
  { id: 'authorities',  title: 'Authorities',          icon: '🏛', color: '#2D2D69' },
  { id: 'legal',        title: 'Legal',                icon: '⚖️', color: '#5B4FCF' },
  { id: 'design',       title: 'Design & Consultants', icon: '📐', color: '#0E6B5E' },
  { id: 'sales',        title: 'Sales & Marketing',    icon: '📣', color: '#E07B39' },
  { id: 'construction', title: 'Construction',         icon: '🏗', color: '#2D6A4F' },
  { id: 'finance',      title: 'Banking & Finance',    icon: '💰', color: '#B5451B' },
];

export const priCfg = {
  High:   { bg: '#FEE2E2', text: '#991B1B', dot: '#EF4444' },
  Medium: { bg: '#FEF3C7', text: '#92400E', dot: '#F59E0B' },
  Low:    { bg: '#ECFDF5', text: '#065F46', dot: '#10B981' },
};
export const stsCfg = {
  'Not Started':       { bg: '#F3F4F6', text: '#6B7280' },
  'In Progress':       { bg: '#DBEAFE', text: '#1E40AF' },
  'Awaiting Response': { bg: '#FEF3C7', text: '#92400E' },
  'Completed':         { bg: '#D1FAE5', text: '#065F46' },
  'On Hold':           { bg: '#F3E8FF', text: '#6B21A8' },
};

export function buildProjects() {
  return [
    {
      id: 'nandroya', name: 'Nandroya', color: '#0E7A6F',
      stage: 'Planning & Approvals',
      purchaseDate: '', settlementDate: '2025-10-13',
      sections: {
        authorities: [
          mkRow('Council', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Gold Coast City Council', '', 'DA Submitted - 13/01/2026\nRFI Responded 15/02/2026 (35 Business Days to respond) Due 03/04/2026', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Energex', '', '', [{ action: 'Confirmation on Upgrade of Isolator to PMT from PECE', person: 'AL', due: '2026-03-20', priority: 'High', status: 'In Progress', manualFlag: false }]),
          mkRow('Gold Coast Water', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        legal: [
          mkRow('Johanson Lawyers', '', 'Community title Document', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        design: [
          mkRow('Architect', '', '', [{ action: '- SALT - Review Detailed Design Documentation \n- Stuart to Provide L Shape Kitchen - Wed 01/04\n- Stuart to provide all consultant quotes\n- Stuart to provide Steel install quote\n- Interiors & book Meeting with Stu for this week', person: 'SS/AL', due: '2026-03-14', priority: 'High', status: 'In Progress', manualFlag: false }]),
          mkRow('Survey', '', 'Proposed POS for Units (Disclosure Plan)', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Elec engineer', 'Peter Eustace Consulting Engineers', '', [{ action: 'PECE to provide: \n- Preliminary Design Timings\n- Preliminary Design comments. \n- New PMT confirmation \n- ECI Pricing. Internal & External Breakdown. \n- Send Updated DD & Civil Package to PECE', person: 'SS/AL', due: '2026-03-20', priority: 'High', status: 'In Progress', manualFlag: false }]),
          mkRow('Traffic & Waste', 'Jason - Legend Consulting', '- RFI Traffic Comments Addressed', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Landscape Architect', 'I-Primus Landscape Design & Planning - Loren', '- RFI Comments Addressed', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Civil Engineer', 'Jason - Legend Consulting', '- Detailed Design Submitted. \n- RFI Response Submitted. \n- Non Approved Storm Water Filtration System - Awaiting Approval if not update design', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Structural Engineer', '', '- Building Structural Quotes tendered by Osmans. \n- Review Quotes. \n\nRetaining Wall Structural Quotes.  \n- To Engage \n- Get Quotes. \n- SS to Speak to Pete for Structural Eng.', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Hydraulic Engineer', 'Hydraulic Design Solutions', '- Design received to be reviewed. \n- Send to Jason for Review', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Geotech', 'Protest Engeineering', '- Report Updated Through RFI Process', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Arborist', 'Herritage Tree Care - Tony', '- Review Arborist Report \n- Organise Tree Management Plan Once DA is Approved', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Building Certifier', '', '- Review Both Quotes \n- Engage Certifier\n- Reccomendations on Mechanical, Fire Saftey, Any additional Items', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Mechanical Engineer', '', 'Certifier to confirm', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Energy Rater', '', '- Stuart Osman to provide Energy Rater Quote (Timing & Cost) \n- Shannon\'s reccomendation to update quote. (Thermal Assesments Australia) TAA', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Town planner', 'HPC Consulting - Murray Wright', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Bushfire Consultant', '', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        sales: [
          mkRow('Content Planner', '', '1BD Sales Strategy\nRental Invesments', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Ivy Street', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Engage', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Drip Campaign', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Channels', '', 'Investment Brochure to be Prepared', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Affordable Housing', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Sales Office', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ESG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        construction: [
          mkRow('Civil', '', '- BOQ. - SS \n- Shannon - To begin tendering \n- Back up Storm Water - Timing & availbility  \n- Program. - SS to build out over the fortnight \n-Sewer & Water Before Built form or After.  SS/AL Speak to Stuart', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Built Form', '', 'Tender Stuart & Other Options. \n- Pricing Breakdown/ BOQ \n- Program. \n- Staged Timings.', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        finance: [
          mkRow('Purchase Date', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Hurdles', '', '- Understand Build Cost. \n- Understand Civil Cost.\n- Understand Elec Timing & Cost.', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Accounting', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PCG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Invoices', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Feaso', '', '- CB to Send AL Feaso. \n- AL to build new Feaso. \n- Built Form $3,000 per SQM & $4,000 per SQM\n- Civil $1,500,000 + Electrical $500,000', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Valuers', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Debt', '', 'Current Debt: $1.154m at 12%\nSettled 13th October 2025\n12 Month Term capatilised', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('QS', '', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SRA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ACC', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SOCT', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('CSA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
      },
    },
    {
      id: 'jimboomba', name: 'Meadowview Jimboomba', color: '#1B3A5C',
      stage: 'Planning & Approvals',
      purchaseDate: '', settlementDate: '2025-03-17',
      sections: {
        authorities: [
          mkRow('Council', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Logan City Council', '', '', [{ action: '- Awaiting OW \nTP to submit Ecological Data/ Email', person: 'CS', due: '2026-03-30', priority: 'High', status: 'In Progress', manualFlag: false }]),
          mkRow('Energex', '', '', [{ action: 'PECE to submit with Energex - AL to check in', person: 'AL', due: '2026-03-20', priority: 'High', status: 'In Progress', manualFlag: false }]),
          mkRow('Logan Water', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        legal: [
          mkRow('Johanson Lawyers', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        design: [
          mkRow('Survey', 'Andrew & Hanson', 'Proposed POS for Units (Disclosure Plan)', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Elec engineer', 'Peter Eustace Consulting Engineers', '', [{ action: 'PECE to provide: \n- Preliminary Design Timings\n- Preliminary Design comments. \n- ECI Pricing. Internal & External Breakdown. \n- Send Updated DD & Civil Package to PECE', person: 'SS/AL', due: '2026-03-20', priority: 'High', status: 'In Progress', manualFlag: false }]),
          mkRow('Traffic & Waste', 'Jason - Legend Consulting', '- Road Closure Traffic Permits. - SS', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Landscape Architect', 'I-Primus Landscape Design & Planning - Loren', 'No Action Items', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Civil Engineer', 'Jason - Legend Consulting', '- Detailed Design Submitted. \n- RFI Response Submitted.', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Geotech', 'Protest Engeineering', '- Test pitts.', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Arborist', 'QFC', '- Pre & Post Clearing Report - CB', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Town planner', 'Ultimate Planning Solutions - Chris Selton', '- Ecologist Email to Council. \n- Offset Recalculation', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Bushfire Consultant', '', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Ecology  Ultimate Planning Solutions', 'Graham Dart', '- Review Offset Sites', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Fisheries', 'Aquatic Bio Passage - Andrew Berghuis', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        sales: [
          mkRow('Content Planner', '', '- Coming Soon Page Ad \n- Billboard', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('House', '', '- Building Cleaner - 10/04 - Need to Find.\n- Painter - Robo\'s Handy Man - Booked - Start Date 12/04. \n- Tiler - Dexter ($$) - Need to be organised - Start on 15/04. \n- Electrical - T42 Electrical Fabian - Need to be booked - 19/04\n- Plumbing - Josh Brown Plumbing - Need to be booked - 19/04\n\n- Tidy Up Drivway & Clean Up Rubbish - 10-11/04', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('CB', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Drip Campaign', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Channels', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Affordable Housing', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Sales Office', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ESG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        construction: [
          mkRow('Civil', '', '- BOQ. - Received from Jason - SS to revise\n- Program. - SS to build out over the fortnight \n- Dig Right - To provide pricing. \n- Sewer & Water Before Built form or After.  SS/AL Speak to Stuart', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        finance: [
          mkRow('Purchase Date', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Hurdles', '', '- Offset Site', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Accounting', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PCG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Invoices', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Feaso', '', '- CB to Send AL Feaso. \n- AL to build new Feaso. \n- $2.8m Purchase Price - No Debt but Owes Stockleigh', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Valuers Savils - Amy', '', '- Due Next Week 07/03\n- CS to follow Up', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Debt', '', 'No Debt', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('QS', '', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SRA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ACC', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SOCT', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('CSA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
      },
    },
    {
      id: 'stockleigh', name: 'Meadowview Stockleigh', color: '#C9A84C',
      stage: 'Construction',
      purchaseDate: '', settlementDate: '2025-03-17',
      sections: {
        authorities: [
          mkRow('Council', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Logan City Council', '', '05/11/26 Landscape Bond Return \n$133,942.96', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Energex', '', 'Bond Due this week. $30k', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Logan Water', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        legal: [
          mkRow('Johanson Lawyers', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        design: [
          mkRow('Survey', 'Andrew & Hanson', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Elec engineer', 'Peter Eustace Consulting Engineers', 'Lightpole Repair East cost repair', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Traffic & Waste', 'Jason - Legend Consulting', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Landscape Architect', 'I-Primus Landscape Design & Planning - Loren', 'Plant Street Trees - 05/05/2026\n- Tender out works.', [{ action: '', person: 'CB/SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Civil Engineer', 'Jason - Legend Consulting', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Geotech', 'Protest Engeineering', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Arborist', 'QFC', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Town planner', 'Ultimate Planning Solutions - Chris Selton', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Bushfire Consultant', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Ecology  Ultimate Planning Solutions', 'Graham Dart', '- Quarterly Maintenance Reports - Southern Cross Regen. \n- Stay ontop of them.\n- Next Report - April \n- Need to slash', [{ action: '', person: 'CS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Fisheries', 'Aquatic Bio Passage - Andrew Berghuis', '- Follow Up Reporting - Courtesy Call', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        sales: [
          mkRow('Old House', '', '- Paint Roof. - Get Quotes\n- Install Driveway - 10/04 Pete & Mitch\n- Install Watermeter - Pete to complete Application URGENT\n- Landscape - Review Yard and buy plants', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Whole Site', '', '- Fencing - Follow up for commitment. \n- Laser Cut Entry piece sign. - SS to arrange\n- Maintenance Mow', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Drip Campaign', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Channels', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Affordable Housing', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Sales Office', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ESG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        construction: [
          mkRow('Civil', '', '- BOQ. - Received from Jason - SS to revise\n- Program. - SS to build out over the fortnight \n- Dig Right - To provide pricing. \n- Sewer & Water Before Built form or After.  SS/AL Speak to Stuart', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        finance: [
          mkRow('Purchase Date', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Hurdles', '', '- Offset Site', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Accounting', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PCG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Invoices', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Feaso', '', '- CB to Send AL Feaso. \n- AL to build new Feaso. \n- $2.8m Purchase Price - No Debt but Owes Stockleigh', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Valuers Savils - Amy', '', '- Due Next Week 07/03\n- CS to follow Up', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Debt', '', 'No Debt \n- Equity Release to fund Bonogin', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('QS', '', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SRA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ACC', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SOCT', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('CSA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
      },
    },
    {
      id: 'mudgeeraba', name: 'Mudgeeraba', color: '#E07B39',
      stage: 'Planning & Approvals',
      purchaseDate: '', settlementDate: '2024-10-01',
      sections: {
        authorities: [
          mkRow('Council', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Gold Coast City Council', '', '- DA Submission Paused. Council Refusal\n- Afflux Issues - Outside of tolerances\n- 30M Creek Buffer \n- Need to organise Onsite council meeting.', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Energex', '', 'Awaiting DA', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Logan Water', '', 'Awaiting DA', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('TMR', '', '- RFI Response Submitted - 17/03/2026 - Response due 17/04/2026', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        legal: [
          mkRow('Johanson Lawyers', '', '- Community Title Scheme', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        design: [
          mkRow('Survey', 'Andrew & Hanson', 'Proposed POS for Units (Disclosure Plan)', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Elec engineer', 'Peter Eustace Consulting Engineers', '', [{ action: 'PECE to provide: \n- Preliminary Design to be stopped. \n- Preliminary Design comments. \n- ECI Pricing. Internal & External Breakdown.', person: 'SS/AL', due: '2026-03-20', priority: 'High', status: 'In Progress', manualFlag: false }]),
          mkRow('Traffic & Waste', 'Jason - Legend Consulting', 'No Action Items', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Landscape Architect', 'I-Primus Landscape Design & Planning - Loren', '- Review RFI Response & redesign Landscape \n- Look into tiered retaining wall option based on TMR response', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Civil Engineer', 'Jason - Legend Consulting', '- Afflux recalculation & solution - 31/03.\n- 30m Buffer Zone - Seeking relaxation no action.', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Geotech', 'Protest Engeineering', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Arborist', 'QFC', '- Pre & Post Clearing Report - CB', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Town planner', 'Ultimate Planning Solutions - Chris Selton', '- Understand Additonal Reports that can assist case - EG Ecology to support 30m offset.', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Bushfire Consultant', '', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Ecology  Ultimate Planning Solutions', 'Graham Dart', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Fisheries', 'Aquatic Bio Passage - Andrew Berghuis', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Acoustic Palmer Acoustic', 'Javier Navas', 'TMR RFI - Management', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        sales: [
          mkRow('Content Planner', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Gallery', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('CB', '', '- David Wright - House relocators', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Drip Campaign', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Channels', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Affordable Housing', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Sales Office', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ESG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        construction: [
          mkRow('Civil', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        finance: [
          mkRow('Purchase Date', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Hurdles', '', '- DA Approval.', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Accounting', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PCG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Invoices', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Feaso', '', '- CB to Send AL Feaso. \n- AL to build new Feaso. \n- $2.275 9% Dave - 100% 2yrs cap', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Valuers', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Debt', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('QS', '', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SRA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ACC', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SOCT', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('CSA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
      },
    },
    {
      id: 'bonogin', name: 'Bonogin Valley Estate', color: '#2D6A4F',
      stage: 'Planning & Approvals',
      purchaseDate: '2025-12-16', settlementDate: '2026-06-26',
      sections: {
        authorities: [
          mkRow('Council', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Gold Coast City Council', '', '- DA Submission This week', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Energex', '', 'Awaiting DA', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Gold Coast City Water', '', 'Awaiting DA', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('TMR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        legal: [
          mkRow('Johanson Lawyers', '', '- Send DA Packag. \n- Contract Void Date - 08/04/2026', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        design: [
          mkRow('Survey', 'Andrew & Hanson', 'Proposed POS for Units (Disclosure Plan)', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Elec engineer', 'Peter Eustace Consulting Engineers', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Traffic & Waste', 'Jason - Legend Consulting', 'No Action Items', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Landscape Architect', 'I-Primus Landscape Design & Planning - Loren', '- Awaiting Package - 30/01', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Civil Engineer', 'Jason - Legend Consulting', '- Awaiting Civil Design - 30/1', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Geotech', 'Protest Engeineering', '- Landslide Report Complete', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Arborist', 'QFC', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Town planner', 'HPC Consulting - Murray Wright', '- Preperation of DA Package', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Bushfire Consultant', '', '- Awaiting Report - 30/01', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Ecology  Ultimate Planning Solutions', 'Graham Dart', '- Reports complete for DA.', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        sales: [
          mkRow('Content Planner', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Gallery', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Marketing', '', '- Engage Graya \n- Full Marketing Package', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Drip Campaign', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Channels', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Affordable Housing', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Sales Office', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ESG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        construction: [
          mkRow('Civil', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        finance: [
          mkRow('Hurdles', '', '- DA Approval.', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Accounting', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PCG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Invoices', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Feaso', '', '- CB to Send AL Feaso. \n- AL to build new Feaso. \n- $5,555,000+ $300k per lot over 14 lots. \n- only paid deposit', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Valuers', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Debt', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('QS', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SRA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ACC', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SOCT', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('CSA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
      },
    },
    {
      id: 'goonellabah', name: 'Goonellabah', color: '#5B4FCF',
      stage: 'Planning & Approvals',
      purchaseDate: '', settlementDate: '2024-08-23',
      sections: {
        authorities: [
          mkRow('Council', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Lismore City Council', '', '- Awaiting Minor Change Modification \n- Public Notice Finished 25/03\n- Response Expected - 10/03 Latest\n\n- Surplus Land to be included in future urban footprint (Draft Urban Plan)\n- 14/04/2026 Expected date', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Essential Energy', '', 'Awaiting DA', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Gold Coast City Water', '', 'Awaiting DA', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('TMR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        legal: [
          mkRow('Johanson Lawyers', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        design: [
          mkRow('Survey', 'Andrew & Hanson', '- Locate Sewer Man hole', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Elec engineer', 'Peter Eustace Consulting Engineers', '', [{ action: 'No Action', person: 'SS/AL', due: '2026-03-20', priority: 'High', status: 'In Progress', manualFlag: false }]),
          mkRow('Traffic & Waste', 'Jason - Legend Consulting', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Landscape Architect', 'I-Primus Landscape Design & Planning - Loren', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Civil Engineer', 'Jason - Legend Consulting', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Geotech', 'Protest Engeineering', '- Geotech Investigation', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Arborist', 'QFC', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Town planner', 'HPC Consulting - Murray Wright', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Bushfire Consultant', '', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Ecology  Ultimate Planning Solutions', 'Graham Dart', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        sales: [
          mkRow('Content Planner', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Gallery', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Marketing', '', 'Off Market Sale Campagin - Finishes 02/04', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Drip Campaign', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Channels', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Affordable Housing', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Sales Office', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ESG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        construction: [
          mkRow('Civil', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        finance: [
          mkRow('Purchase Date', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Hurdles', '', '- Draft Urban Plan Inclusion. \n- Valuation\n- Off Market Sale Campaign', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Accounting', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PCG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Invoices', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Feaso', '', '- CB to Send AL Feaso. \n- $2,000,000 12% - 2yr Term - Dave 100%', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Valuers Charter Kremer -', '', '- 50% Valuation - 17/04 \n- Full Valuation - 5 Days later', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Debt', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('QS', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SRA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ACC', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SOCT', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('CSA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
      },
    },
    {
      id: 'bilambil', name: 'Bilambil', color: '#B5451B',
      stage: 'Planning & Approvals',
      purchaseDate: '', settlementDate: '2022-03-02',
      sections: {
        authorities: [
          mkRow('Council', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Tweed City Council', '', '- Modification Submission \n- Waiting on Council to provide Invoice\n- Documentation Submitted 12/03/2026', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Essential Energy', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Tweed Water', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('TMR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        legal: [
          mkRow('Johanson Lawyers', '', '- Community Title Scheme', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        design: [
          mkRow('Survey', 'Andrew & Hanson', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Elec engineer', 'Peter Eustace Consulting Engineers', '', [{ action: '- CB/AL to Follow Up and check design submission. \n- Design Completed \n- Timing.', person: 'SS/AL', due: '2026-03-20', priority: 'High', status: 'In Progress', manualFlag: false }]),
          mkRow('Traffic & Waste', 'Jason - Legend Consulting', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Landscape Architect', 'I-Primus Landscape Design & Planning - Loren', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Civil Engineer', 'Jason - Legend Consulting', '- Lodge CC Once Modification is approved. \n- Design Complete', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Geotech', 'Protest Engeineering', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Arborist', 'QFC', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Town planner', 'Ultimate Planning Solutions - Chris Selton', '- Mod Lodgement Follow Up', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Bushfire Consultant', '', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Ecology  Ultimate Planning Solutions', 'Graham Dart', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        sales: [
          mkRow('Content Planner', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Gallery', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Marketing', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Drip Campaign', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Channels', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Affordable Housing', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Sales Office', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ESG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        construction: [
          mkRow('Civil', '', 'Awaiting CC Approval', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        finance: [
          mkRow('Purchase Date', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Hurdles', '', '- Modification Approval', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Accounting', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PCG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Invoices', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Feaso', '', '- CB to Send AL Feaso. \n- $2,000,000 10% - $600k Ivett @10% $1,400,000 @7%', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Valuers Charter Kremer -', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Debt', '', '$1,400,000 @7% Ivette Servicing Loan', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('QS', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SRA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ACC', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SOCT', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('CSA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
      },
    },
    {
      id: 'canungra', name: 'Canungra – Dave', color: '#7B5EA7',
      stage: 'Land Acquisition',
      purchaseDate: '', settlementDate: '',
      sections: {
        authorities: [
          mkRow('Council', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Scenic Rim Council', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Essential Energy', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Tweed Water', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('TMR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Federal', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        legal: [
          mkRow('Johanson Lawyers', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        design: [
          mkRow('Survey', 'Andrew & Hanson', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Elec engineer', 'Peter Eustace Consulting Engineers', '', [{ action: 'No Action', person: 'SS/AL', due: '2026-03-20', priority: 'High', status: 'In Progress', manualFlag: false }]),
          mkRow('Traffic & Waste', 'Jason - Legend Consulting', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Landscape Architect', 'I-Primus Landscape Design & Planning - Loren', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Civil Engineer', 'Jason - Legend Consulting', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Geotech', 'Protest Engeineering', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Arborist', 'QFC', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Town planner', 'Ultimate Planning Solutions - Chris Selton', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Bushfire Consultant', '', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Ecology  Ultimate Planning Solutions', 'Graham Dart', 'No Action', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        sales: [
          mkRow('Content Planner', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Gallery', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Marketing', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Drip Campaign', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Channels', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Affordable Housing', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Sales Office', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PR', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ESG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        construction: [
          mkRow('Civil', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
        finance: [
          mkRow('Purchase Date', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Hurdles', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Accounting', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('PCG', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Invoices', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Feaso', '', 'Run Dave Through Feaso', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Valuers Charter Kremer -', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('Debt', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('QS', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SRA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('ACC', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('SOCT', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
          mkRow('CSA', '', '', [{ action: '', person: 'SS', due: '', priority: 'Medium', status: 'Not Started', manualFlag: false }]),
        ],
      },
    },
  ];
}
